"use client";

import type { VerificationResponse } from "@linkoteq/steel-verification-contracts";

const titleMap: Record<string,string>={biaxial_bending:"Biaxial bending",compression_bending:"Compression + bending",tension_bending:"Tension + bending",tension:"Axial tension",compression:"Axial compression",shear_major:"Major-axis shear",shear_minor:"Minor-axis shear"};
const readable=(name:string)=>titleMap[name]??name.replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());
const num=(value:unknown,decimals=2)=>{const n=Number(value??0);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:decimals}):"—"};
const pct=(value:unknown)=>`${(Number(value??0)*100).toFixed(2)}%`;

function EngineeringReport({result}:{result:VerificationResponse}){
  const n:any=result.normalized_inputs??{}, code=n.code??{}, material=n.material??{}, section=n.section??{}, geometry=n.geometry??{}, actions=n.actions??{}, iv:any=result.intermediate_values??{}, values:any=result.values??{}, r:any=result.utilization_ratios??{};
  const v=(key:string)=>values[key]?.display_value??values[key]?.raw_value??0, kN=(x:unknown)=>Number(x??0)/1000, kNm=(x:unknown)=>Number(x??0)/1_000_000, m=(x:unknown)=>Number(x??0)/1000, ok=(ratio:number)=>ratio<=1;
  return <article className="calcReport">
    <section className="calcCover calcPage"><div className="calcDocHeader"><div><strong>Engineering Calculation</strong><span>Report</span></div><div><b>Document ID :</b><span>______________________</span><b>Client Reference # :</b><span>______________________</span></div><div><small>Preparer:</small><span>First & Last Name, affiliation</span><small>Verifier:</small><span>First & Last Name, affiliation</span></div></div><div className="calcTitle"><b>Title:</b><span>Design of W-Sections According to CSA S16:2019 [CISC STRUCTURAL SECTIONS]</span></div><div className="calcNotice"><p>This engineering calculation report documents the structural verification of a CISC W-section in accordance with CSA S16:2019.</p><h3>Important Usage Instructions:</h3><p>Each user is responsible for independently verifying the accuracy and applicability of the calculations and code references before use in any project.</p></div></section>
    <section className="calcPage"><h2>Design Inputs</h2><div className="calcBand"><b>Section</b><strong>{section.section_name_metric||result.section_dataset.designation}</strong><span>{section.section_name_imperial||""}</span></div><h3>A. Reduction Factors</h3><div className="calcTable twoCol"><div><span>Steel strength factor</span><b>ϕs = {num(code.phi_s,3)}</b><small>CSA S16:19 Cl. 13.1</small></div><div><span>Steel ultimate strength factor</span><b>ϕu = {num(code.phi_u,3)}</b><small>CSA S16:19 Cl. 13.1</small></div></div><h3>B. Material Properties</h3><div className="calcTable twoCol"><div><span>Yield strength</span><b>Fy = {num(material.yield_strength)} MPa</b><small></small></div><div><span>Ultimate strength</span><b>Fu = {num(material.ultimate_strength)} MPa</b><small></small></div><div><span>Young's Modulus</span><b>E = {num(Number(material.elastic_modulus)/1000)} GPa</b><small></small></div><div><span>Shear modulus</span><b>G = {num(material.shear_modulus)} MPa</b><small></small></div></div><h3>C. Factored Forces</h3><div className="calcTable twoCol"><div><span>Axial force</span><b>N = {num(kN((actions.tension_force||0)-(actions.compression_force||0)))} kN</b><small>+ tension / − compression</small></div><div><span>Major shear (V1)</span><b>{num(kN(actions.shear_major))} kN</b><small></small></div><div><span>Minor shear (V2)</span><b>{num(kN(actions.shear_minor))} kN</b><small></small></div><div><span>Major moment (M2)</span><b>{num(kNm(actions.moment_major))} kN·m</b><small></small></div><div><span>Minor moment (M1)</span><b>{num(kNm(actions.moment_minor))} kN·m</b><small></small></div></div></section>
    <section className="calcPage"><h3>D. Geometry</h3><div className="calcTable twoCol"><div><span>Lx</span><b>{num(m(geometry.length_major),3)} m</b><small></small></div><div><span>Ly</span><b>{num(m(geometry.length_minor),3)} m</b><small></small></div><div><span>Lz</span><b>{num(m(geometry.length_torsional),3)} m</b><small></small></div><div><span>kx / ky / kz</span><b>{num(geometry.effective_length_factor_major,2)} / {num(geometry.effective_length_factor_minor,2)} / {num(geometry.effective_length_factor_torsional,2)}</b><small></small></div></div><h3>E. Section Properties</h3><div className="calcTable twoCol"><div><span>Area, A</span><b>{num(section.gross_area)} mm²</b><small></small></div><div><span>Depth, d</span><b>{num(section.depth)} mm</b><small></small></div><div><span>Flange width, b</span><b>{num(section.flange_width)} mm</b><small></small></div><div><span>Ix / Iy</span><b>{num(section.moment_of_inertia_major)} / {num(section.moment_of_inertia_minor)} mm⁴</b><small></small></div></div></section>
    <section className="calcPage"><h3>Slenderness Ratio</h3><div className="calcEquation"><span>λx = kx·Lx / rx</span><b>{num(v("slenderness_major"))}</b><small>CSA S16:19 Cl. 10.4.1</small></div><div className="calcEquation"><span>λy = ky·Ly / ry</span><b>{num(v("slenderness_minor"))}</b><small></small></div><h3>Tension Capacity</h3><div className="calcEquation"><span>Tr = min(Tr1, Tr2)</span><b>{num(kN(v("tension_resistance")))} kN</b><small>CSA S16:19 Cl. 13.2</small></div><div className={ok(r.tension)?"calcCheck pass":"calcCheck fail"}>Ratio = {pct(r.tension)}</div><h3>Compression Capacity</h3><div className="calcEquation"><span>Cr</span><b>{num(kN(v("compression_resistance")))} kN</b><small>CSA S16:19 Cl. 13.3</small></div><div className={ok(r.compression)?"calcCheck pass":"calcCheck fail"}>Ratio = {pct(r.compression)}</div></section>
    <section className="calcPage"><h3>Shear & Bending Checks</h3><div className="calcEquation"><span>Major shear resistance</span><b>{num(kN(v("major_shear_resistance")))} kN</b><small></small></div><div className="calcEquation"><span>Minor shear resistance</span><b>{num(kN(v("minor_shear_resistance")))} kN</b><small></small></div><div className="calcEquation"><span>Major moment resistance</span><b>{num(kNm(v("moment_resistance_major")))} kN·m</b><small></small></div><div className="calcEquation"><span>Minor moment resistance</span><b>{num(kNm(v("moment_resistance_minor")))} kN·m</b><small></small></div><h3>Final Verification Summary</h3><div className="calcSummary">{Object.entries(r).map(([name,ratio])=><div key={name}><span>{readable(name)}</span><b>{pct(ratio)}</b><em>{ok(Number(ratio))?"OK":"NG"}</em></div>)}</div><div className={result.overall_status==="PASS"?"calcFinal pass":"calcFinal fail"}><span>Maximum Utilization Ratio</span><strong>{pct(v("max_uls_utilization"))}</strong><b>{result.overall_status}</b></div></section>
  </article>;
}

export function ResultsPanel({result,mode="results"}:{result:VerificationResponse|null;mode?:"results"|"report"}){
  if(mode==="report") return <section className="panel resultsPanel reportMode"><div className="reportTabHeading"><span className="eyebrow">Engineering calculation report</span><h2>Report</h2><button type="button" className="primaryButton generatePdfButton" disabled={!result} onClick={()=>window.print()}>Generate PDF</button></div>{result?<EngineeringReport result={result}/>:<div className="emptyResult"><p>The report will appear here when the current inputs have been calculated.</p></div>}</section>;
  if(!result) return <section className="panel emptyResult"><span className="eyebrow">Engineering output</span><h2>Results</h2><p>Results update automatically from the current inputs.</p></section>;
  const ratios=Object.entries(result.utilization_ratios), governingRatio=result.values.max_uls_utilization?.raw_value??Math.max(0,...ratios.map(([,x])=>x)), pass=result.overall_status==="PASS";
  return <section className="panel resultsPanel"><div className="overallStatusCard"><div className={pass?"statusIcon pass":"statusIcon fail"}>{pass?"✓":"!"}</div><div><span className="eyebrow">Overall status</span><h2>{result.overall_status}</h2><p>{pass?"All required checks are within their acceptance limits.":"One or more checks need attention."}</p></div><div className="utilization governingUtilization"><span>Max. utilization</span><strong>{(governingRatio*100).toFixed(1)}%</strong><small>{readable(result.governing_check??"—")}</small></div></div><div className="checks utilizationChecks"><div className="checksHeading"><span className="eyebrow">All checks</span><h2>Utilization ratios</h2></div>{ratios.map(([name,ratio])=><div className="utilizationRow" key={name}><div className="utilizationRowTop"><strong>{readable(name)}</strong><b>{(ratio*100).toFixed(1)}%</b></div><div className="ratioTrack"><div className="ratioFill" style={{width:`${Math.min(ratio*100,100)}%`}}/></div></div>)}</div></section>;
}
